# Generated by Django 3.2.4 on 2021-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_sellerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discountedPrice', models.FloatField()),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('BW', 'Bottom Wear'), ('TW', 'Top Wear')], max_length=3)),
                ('brand', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='productimg')),
                ('seller', models.IntegerField(default='00')),
            ],
        ),
    ]
