# Generated by Django 3.2.2 on 2021-05-11 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=22)),
                ('product_discountedPrice', models.DecimalField(decimal_places=2, max_digits=22)),
                ('product_category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('BW', 'Bottom Wear'), ('TW', 'Top Wear')], max_length=3)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('ARUNANCHAL PRADESH', 'ARUNANCHAL PRADESH'), ('ASSAM', 'ASSAM'), ('BIHAR', 'BIHAR'), ('CHATTISGARH', 'CHATTISGARH'), ('GOA', 'GOA'), ('GUJRAT', 'GUJRAT'), ('HARYANA', 'HARYANA'), ('HIMANCHAL PRADESH', 'HIMANCHAL PRADESH'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASTRA', 'MAHARASTRA'), ('MANIPUR', 'MANIPUR'), ('ODISHA', 'ODISHA'), ('PUNJAB', 'PUNJAB'), ('RAJASTHAN', 'RAJASTHAN'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('UTTARAKHAND', 'UTTARAKHAND'), ('WEST BENGAL', 'WEST BENGAL')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('PACKED', 'PACKED'), ('SHIPPED', 'SHIPPED'), ('ON THE WAY', 'ON THE WAY'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
