# Generated by Django 3.2.2 on 2021-05-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'cart'},
        ),
        migrations.AlterModelOptions(
            name='confirmation',
            options={'verbose_name_plural': 'confirmation'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customer'},
        ),
    ]
