# Generated by Django 3.2.2 on 2021-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210512_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountedPrice',
            field=models.FloatField(),
        ),
    ]
