# Generated by Django 3.2.2 on 2021-06-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='seller_id',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
